module.exports = {
  MIN_NAME_LENGTH: 3,
  MAX_NAME_LENGTH: 255,
  MIN_GROUP_NAME_LENGTH: 3,
  MAX_GROUP_NAME_LENGTH: 255,
  MIN_PASSWORD_LENGTH: 6,
  MAX_PASSWORD_LENGTH: 100,
  MIN_ID_LENGTH: 1,
  MAX_ID_LENGTH: 255,
  MIN_RACE_LENGTH: 2,
  MAX_RACE_LENGTH: 255,
  MIN_OBSERVATION_LENGTH: 3,
  MAX_OBSERVATION_LENGTH: 255
};