DROP TABLE IF EXISTS usuario;
DROP TABLE IF EXISTS ovino;
DROP TABLE IF EXISTS pesagem;
DROP TABLE IF EXISTS historico_medico;
DROP TABLE IF EXISTS medicamento;
DROP TABLE IF EXISTS grupo;
DROP DATABASE IF EXISTS PostgreSQL;